

const CymroPlans = [
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Active Monitoring",
    "Describe your project, call to action and objective": "Ongoing support to promote Wales delivery",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind's free guided self-help service ",
    "Project Lead": "Kartik Bhalla",
    "Team/Department": "Wales - Wales",
    "Audience ": "Service-users, stakeholders (primary care), staff, general public",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Shout (using all channels)",
    "Project Name": "Dignity and respect in inpatient settings / restraint campaign",
    "Describe your project, call to action and objective": "Pending FOI results from local Health boards, campaign around use of restraint/treatment if people in mental health inpatient units",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC pending lived exp consultation and FOI results",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Shout (using all channels)",
    "Project Name": "CYP info promotion",
    "Describe your project, call to action and objective": "Activity to promote Mind's info  to young people  - Inc. strategic priority areas and Welsh speakers",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "If this speaks to you, speak to Mind",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "Young people in Wales",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Local Mind network in Wales",
    "Describe your project, call to action and objective": "Activity to promote the impact of the network in Wales to encourage use of service and position the network for future funding ops (as per Wales Ambition)",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "TBC",
    "Project Lead": "Elin Lenny",
    "Team/Department": "Wales - Wales",
    "Audience ": "people with mental health problems, stakeholders (commissioners, LHBs etc)",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Mums matter",
    "Describe your project, call to action and objective": "Activity to promote Mums matter as an example of service delivery across the network and promote services to people in Wales",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "Mums matter is an excellent service that can help mums with their mental health",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "stakeholders (commissioners, primary care, Welsh Gov)New mums",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Stroke Association partnership",
    "Describe your project, call to action and objective": "Joint partnership to develop a service for stroke survivors",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "TBC",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Mind Cymru digital strategy",
    "Describe your project, call to action and objective": "increase social media presence and visits to the website from people in Wales",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "TBC",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Mental Health strategy response",
    "Describe your project, call to action and objective": "lived exp consultation to shape mental health strategy response. Research in Q1, publicise response in Q4",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "TBC",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "people with lived experience",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Sort the Switch next phase",
    "Describe your project, call to action and objective": "Campaign is gaining traction in Welsh Gov. Activity planned to keep its public profile and celebrate progress, particularly of the young campaigners",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Sort the Switch from CAMHS to AMHS. Celebrate the progress and the power of young people's voices",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "Campaigners, policy makers",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Shout (using all channels)",
    "Project Name": "Cost of Living brand awareness",
    "Describe your project, call to action and objective": "Promoting Mind's brand an support offers to people in poverty",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "If this speaks to you, speak to us",
    "Project Lead": "Sarah Wilson ",
    "Team/Department": "Wales - Wales",
    "Audience ": "People with mental health problems affected by the cost of living crisis",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Lived experience leadership",
    "Describe your project, call to action and objective": "Mind Cymru is developing a programme of lived experience leadership. Comms activity to promote internally and externally inc. kick off conference on 20th April",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "People with lived experience can shape Mind's work in Wales",
    "Project Lead": "TBC",
    "Team/Department": "Wales - Wales",
    "Audience ": "Internal, charity network",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "New Ambassador work (Proposals and announcements)",
    "Describe your project, call to action and objective": "Working with the celebrity team to recruit an Ambassador for Mind Cymru, and increase our pool of influencers in Wales. ",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "",
    "Project Lead": "Celeb Team / Bethan ",
    "Team/Department": "Wales - Wales",
    "Audience ": "Supporters",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Help through Hardship",
    "Describe your project, call to action and objective": "Help through Hardship is a partnership between Citizens Advice, Mind and the Trussell Trust. Together, we aim to tackle the underlying causes of hardship, including mental health problems, by offering joined-up advice and support services for people on the lowest incomes and campaigning for a more just support system.",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Two nation P&C",
    "Team/Department": "Wales - Wales",
    "Audience ": "Ultimate audience: government decision-makers. Additional audiences: supporters, campaigners, people facing poverty - generally people warm to the cause who will amplify campaign",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Active Monitoring",
    "Describe your project, call to action and objective": "Launch of two-nation programme",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind's guided self-help service is available to support any adult with mild to moderate mental health problems across England, Wales and the Channel Islands.",
    "Project Lead": "Kartik Bhalla",
    "Team/Department": "Wales - Wales",
    "Audience ": "Service-users, stakeholders (primary care), staff, general public",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Co-op: Information in the Community (Information)",
    "Describe your project, call to action and objective": "Improving the inclusivity and accessibility of Mind's 'seeking help for your mental health' information for our SPAs and distributing it into 14k community settings",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Jenny Knight (comms), Shifa Mehmet (Research), Jessie Coupe (Info), Emily Shackley (Project Manager)",
    "Team/Department": "Wales - Wales",
    "Audience ": "TBC (awaiting insights)",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "ITV Britain Get Talking 2023 campaigns",
    "Describe your project, call to action and objective": "TBC on the exact campaign plans, however they are likely to follow a similar format to the previous BGT campaigns- breakthrough moments on live ITV programmes, encouraging the general public to open up and talk about their mental health",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "CP: StephJen WaltersMedia: Alex Bushill, Steph Cade",
    "Team/Department": "Wales - Wales",
    "Audience ": "ITV viewers Inc. Wales",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "ASICS 'Poetry in Motion'",
    "Describe your project, call to action and objective": "ASICS campaign asking customers to capture feeling that movement gives them. Donation to Mind for each submission. Dates tbc but should be roughly this.",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Exact messaging tbc. Will be something about taking focus away from pressure of exercise (PBs, weight loss etc) and focuSing on how it makes you feel",
    "Project Lead": "Megan Earl, Emily Hall",
    "Team/Department": "Wales - Wales",
    "Audience ": "ASICS customers",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "MHAW Welsh cut",
    "Describe your project, call to action and objective": "TBC",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Sarah Wilson ",
    "Team/Department": "Wales - Wales",
    "Audience ": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "YouTube video project ",
    "Describe your project, call to action and objective": "YouTube-funded work to create 21 videos on 3 key MH topics: eating problems, depression, personality disorders. Inc. Welsh language",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "",
    "Project Lead": "Rachel Q/Sarah Miles/Kerry McLeod",
    "Team/Department": "Wales - Wales",
    "Audience ": "Adults in England and Wales ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Direct Line & Mind collaboration",
    "Describe your project, call to action and objective": "Survey around CYP and mental health, including a 'moment' with rapper Marc Jones",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Importance of self care and acceptance. Campaign is based around the concept of 'love yourself'",
    "Project Lead": "Shelly Naylor",
    "Team/Department": "Wales - Wales",
    "Audience ": "Young People, parents, general public",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "EFL Legacy grants - Hum tbc Q1/2 ",
    "Describe your project, call to action and objective": "TBC press launch of 10 legacy projects /social media spotlight if appropriate ",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "Whoever you support, Mind supports you. ",
    "Project Lead": "Cameron Milller/Hayley Jarvis ",
    "Team/Department": "Wales - Wales",
    "Audience ": "General public /Sport and physical activity sector Inc. in Wales",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "ASICS Get Active Connector Launch - Hum tbc Q1/2",
    "Describe your project, call to action and objective": "TBC press launch regionally with 4 x projects and a national event/launch with Mind and ASICS ",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "What is your key message?": "Being active supports you to stay well and live well. ",
    "Project Lead": "Cameron Milller/Hayley Jarvis ",
    "Team/Department": "Wales - Wales",
    "Audience ": "General public /Sport and physical activity sector ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "": "",
    "S": "",
    "M": "",
    "T": "",
    "W": "",
    "F": ""
  }
]
module.exports = CymroPlans

