const rows1 = [    
    {
      "What type of moment is this project?": "Sing",
      "Project Name": "ALWAYS ON: Speaking engagement promotion linked with key mental health moments ",
      "Describe your project, call to action and objective": "Promotion of our speaking engagement services i.e. webinars/lunch and learns 10-12 weeks in advance of relevant key mental health moment ",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "This <insert key mental health date> Mind can support you to increase your employees’ understanding of <insert key date theme> and how to support their own mental health and wellbeing through our speaking engagement offering. ",
      "Project Lead": "Josh M",
      "Team/Department": "FWW – FundraiSing Workplace Wellbeing", 
      "Who is your target audience?": "L&D Leads / HR Professional s",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    },
    {
      "What type of moment is this project?": "Sing",
      "Project Name": "ALWAYS ON: WW Public access training promotion ",
      "Describe your project, call to action and objective": "Promotion of our annual WW public access training programme open to individuals in work ",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "Everyone has mental health just as we have physical health and its important that we have the skills and knowledge to <support ourselves / support our colleagues / appropriately manage our teams / best serve our customers>. Mind’s public access training courses provides Mind’s expert, evidence- based training to individual employees. Find out more about our courses, our course timetable and how to book yourself on to our next course by visiting LINK. ",
      "Project Lead": "Joshm",
      "Team/Department": "FWW – FundraiSing Workplace Wellbeing",
      "Who is your target audience?": "L&D Leads / HR Professional s",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    },
    {
      "What type of moment is this project?": "Hum",
      "Project Name": "INDEX AWARDS: Live coverage and reactive response to partipant social ",
      "Describe your project, call to action and objective": "Live posts to LinkedIn and Twitter sharing our Index awards - Broze, Silver, Gold awards. Top employer. Employee recognition. Responding to corporate accounts sharing their own awards with the public. ",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "The Workplace Wellbeing Index is the foremost benchmark in workplace wellbeing and employee mental health. We recognise and celebrate those organisations who work with us in improving employee mental health. ",
      "Project Lead": "Comms Production",
      "Team/Department": "FWW – Fundraising Workplace Wellbeing",
      "Who is your target audience?": "Business professionals / General public ",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    },
    {
      "What type of moment is this project?": "Hum",
      "Project Name": "INDEX AWARDS: Top Employer Announcement ",
      "Describe your project, call to action and objective": "Announcement of our Top Employer through sharing their video case study. Video published to YouTube. Announcement published to LinkedIn / Twitter / Website. ",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "The Workplace Wellbeing Index is the foremost benchmark in workplace wellbeing and employee mental health. We recognise and celebrate those organisations who work with us in improving employee mental health. ",
      "Project Lead": "TBC",
      "Team/Department": "FWW – Fundraising Workplace Wellbeing",
      "Who is your target audience?": "Business professionals / General public ",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    },
    {
      "What type of moment is this project?": "Hum",
      "Project Name": "INDEX Awards: Award Listing ",
      "Describe your project, call to action and objective": "Update to our Index Awards listing on the Mind website",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "The Workplace Wellbeing Index is the foremost benchmark in workplace wellbeing and employee mental health. We recognise and celebrate those organisations who work with us in improving employee mental health. ",
      "Project Lead": "TBC",
      "Team/Department ": "FWW – Fundraising Workplace Wellbeing",
      "Who is your target audience?": "Business professionals / General public ",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    },
    {
      "What type of moment is this project?": "Sing",
      "Project Name": "LAUNCH: Workplace Wellbeing Snapshot",
      "Describe your project, call to action and objective": "At the end of July we are launching a new Workplace Wellbeing commercial product - the Workplace Wellbeing Snapshot. This benchmarking tool is available year round, results available in just 10 weeks and shorter in duration than our annual Workplace Wellbeing Index. ",
      "Select the central strategic pillar that this activity links to": "We support minds",
      "What is your key message?": "Key messages being finalised 3 April with comms colleagues",
      "Project Lead": "Josh M / Paul Woodruff",
      "Team/Department ": "FWW – Fundraising Workplace Wellbeing",
      "Who is your target audience?": "L&D Leads / HR Professional s",
      "Website": "",
      "Mind at Work": "",
      "Emails": "",
      "Networks": "",
      "Retail": "",
      "Supporter comms": "",
      "Social media": "",
      "Internal": "",
      "Media": "",
      "MPs": "",
      "Celebrity amplifier": "",
      "Corporate amplifier": "",
      "Outdoor": "",
      "M": "",
      "T": "",
      "W": "",
      "F": "",
      "S": ""
    }
  ]
const data2 = [
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Help through Hardship",
    "Describe your project, call to action and objective": "Help through Hardship is a partnership between Citizens Advice, Mind and the Trussell Trust. Together, we aim to tackle the underlying causes of hardship, including mental health problems, by offering joined-up advice and support services for people on the lowest incomes and campaigning for a more just support system.",
    "Select the strategic development priority that this activity links to": "Poverty",
    "What is your key message?": "TBC",
    "Project Lead": "Emily Cowan",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "Ultimate audience: government decision-makers. Additional audiences: supporters, campaigners, people facing poverty - generally people warm to the cause who will amplify campaign",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Blue Light",
    "Describe your project, call to action and objective": "Our Blue Light Programme is here to support emergency responders. We do this through the Blue Light Together website and our monthly newsletter.",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Visit Blue Light Together for information and support tailored to emergency services personnel",
    "Project Lead": "Emily Cowan",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "emergency responders",
    "Website": "",
    "Mind at Work": "",
    "Emails": "X",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "X",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Mental Health and Productivity Pilot",
    "Describe your project, call to action and objective": "MHPP aims to support Midlands business communities and their employees by improving workplace mental health and reducing the impact it has on sickness absence, presenteeism and productivity.",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Sign up to MHPP for a free, bespoke service to help improve your employees' mental health",
    "Project Lead": "Kartik Bhalla",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "Employers in the Midlands",
    "Website": "",
    "Mind at Work": "X",
    "Emails": "X",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Supported self-help (Active Monitoring)",
    "Describe your project, call to action and objective": "Wales delivery as part of Mind's transformation funding",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Mind's guided self-help service is available to support any adult with mild to moderate mental health problems in Wales.",
    "Project Lead": "Kartik Bhalla",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "WALES Service-users, stakeholders (primary care), staff, general public",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "X",
    "Networks": "X",
    "Retail": "X",
    "Supporter comms": "X",
    "Social media": "X",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Co-op: Information in the Community (Information)",
    "Describe your project, call to action and objective": "All",
    "Select the strategic development priority that this activity links to": "Improving the inclusivity and accessibility of Mind's 'seeking help for your mental health' information for our SPAs and distributing it into 14k community settings",
    "What is your key message?": "TBC",
    "Project Lead": "Jenny Knight (comms), Shifa Mehmet (Research), Jessie Coupe (Info), Emily Shackley (Project Manager)",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "Adults (particularly those experience poverty and from racialised communities), and CYP (11-18)",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "X",
    "Networks": "X",
    "Retail": "X",
    "Supporter comms": "",
    "Social media": "TBC",
    "Internal": "X",
    "Media": "X",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "X",
    "Outdoor": "X",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Co-op: Information in the Community (eLearning)",
    "Describe your project, call to action and objective": "All",
    "Select the strategic development priority that this activity links to": "Creating an open-access, online learning course to empower people in communities to support others in their communities.",
    "What is your key message?": "TBC",
    "Project Lead": "Jenny Knight (comms), Shika Naidu (eLearning),  Emily Shackley (Project Manager)",
    "Team/Department": "FP - Funded Programmes",
    "Who is your target audience?": "Community members/leaders aged 18+",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "X",
    "Networks": "X",
    "Retail": "X",
    "Supporter comms": "",
    "Social media": "X",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  }
]

const data3 = [
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Always on Event recruitment ",
    "Describe your project, call to action and objective": "Using PPC to promte events indivduals can sign up to year rounf",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Take on this event and join team mind",
    "Project Lead": "Nicola Seager",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Cold",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Facebook Challenge ",
    "Describe your project, call to action and objective": "Recruit particpants to the challenge",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Run a Marathon in May",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Warm - Past facebook challengersCold - Male and female, 24-65, uk wide",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Facebook Challenge ",
    "Describe your project, call to action and objective": "Recruit particpants to the challenge",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "TBC Cycle Challenge June",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Warm - Past facebook challengersCold - Male and female, 24-65, uk wide",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Weddings",
    "Describe your project, call to action and objective": "Support Mind at your wedding",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Show you care about mental health by supporting Mind on your big day with our wedding favours, or by asking your guests for donations to Mind instead of wedding gifts.",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Cold",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Stream for Mind",
    "Describe your project, call to action and objective": "Recruit particpants to the fundraiser",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Let's show everyone with a mental health problem that they are not alone. Stand with us and fight for mental health by fundraising as you stream",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Warm - Past gaming participantsCold - Male and female, 24-45, uk wide",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Strava Challenge",
    "Describe your project, call to action and objective": "Recruit particpants to the challenge",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Complete 50km on starva over the month of February",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Warm - Past challengersCold - Male and female, 18-65, uk wide",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Stadium stair climb pilot",
    "Describe your project, call to action and objective": "Recruit particpants to the challenge",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Vicky Urquhart",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Warm - Past challengersCold - Male and female, 18-65, uk wide",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Do Your own Running",
    "Describe your project, call to action and objective": "lead gen to recruit particpants to do their own running event",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "You can run in any event for Mind or create your own! Just register with us and join #TeamMind",
    "Project Lead": "Maria Khosla",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Equal split of men and women aged 25-45",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "DYO spring recruitment",
    "Describe your project, call to action and objective": "Sign up to do you own fundraising for Mind",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Maria Khosla",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Equal split of men and women aged 25-45",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Event recruitment",
    "Describe your project, call to action and objective": "Third party event recruitment ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Take on (specific challenge) and join team mind",
    "Project Lead": "Nicola Seager",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Equal split of men and women aged 25-45",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "DYO Aututmn",
    "Describe your project, call to action and objective": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Students",
    "Describe your project, call to action and objective": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Schools",
    "Describe your project, call to action and objective": "To promote our schools/colleges fundraising product to warm contacts who are teachers at schools/colleges that are already engaged with us at Mind",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "Supporting young people – with a focus on traumaFighting for people in poverty ",
    "What is your key message?": "",
    "Project Lead": "Katie Quick",
    "Team/Department": "FE - Fundraising Events",
    "Who is your target audience?": "Teachers at schools / colleges",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "NPD 1",
    "Describe your project, call to action and objective": "",
    "Select the central strategic pillar that this activity links to": "",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "",
    "Team/Department": "",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": ""
  }
]

const fidgeplans = [
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Pause Always on",
    "Describe your project, call to action and objective ": "Pause Subscription box offer",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Pause Product Lead",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Female 25-45",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Pause Subscription/Single -  Gifting",
    "Describe your project, call to action and objective ": "Pause Subscription/Single -  Gifting",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Pause Single (TBC)",
    "Describe your project, call to action and objective ": "Single Pause Subscription offer in line with MHAW",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Organisations/Business",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Pause Single - WORK",
    "Describe your project, call to action and objective ": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Pause Fulfilment & Stewardship",
    "Describe your project, call to action and objective ": "Briefing in Q1  In month six of the Pause boxes there is a ‘More for Mind’ ask in which we ask subscribers whether they would like to keep their monthly payments but not receive the boxes, converting the subscriber to a regular giver. In month 12 we advise that the journey will change so rather than the 12 Pause boxes, they will receive three Pause-style boxes while they still give monthly (RGIW journey).For those who were gifted Pause, the month 12 box includes a cross over ask for them to start the RGIW journey.",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Alicia Shelly",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Legacy: Wills Guide always on ",
    "Describe your project, call to action and objective ": "Offering Mind's Wills Guide to older audiences / Legacy prospects",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Download your free Gifts in Wills Guide and support Mind",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "65+ ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Legacy Stewardship – Calendar ",
    "Describe your project, call to action and objective ": "Q2, This will be a legacy specific variant of the calendar mailing sent by the IG retention team. We intend for the calendar to also be sent to Legacy Pledgers as an additional stewardship touch point. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Legacy Pledger Christmas Card mailing ",
    "Describe your project, call to action and objective ": "Q3 We send a festive card to our legacy pledgers to thank them for their ongoing support at the end of the year and to wish them a joyful festive season from the legacy team. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Warm Audience ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Legacy Pledger Pack ",
    "Describe your project, call to action and objective ": "Q1 and Q2 This is a thank you pack sent to Legacy Pledgers when they commit to leaving us a gift in their will. It gives them more details on how their pledge supports us and offers them the chance to share their story with us. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Free Wills Month",
    "Describe your project, call to action and objective ": "Q3, and Q4 The campaign invites the public to have a simple will written or updated for free. Importantly, it asks them to consider leaving a gift to Mind though there is no obligation to do so. It is run in consortia with a number of other charities",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Ellie Franklin",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Cold Audience ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Warm Wills Mailing",
    "Describe your project, call to action and objective ": "Q2 and Q4 This is a postal and e-appeal to be sent in Q2 (early October), which promotes gifts in wills to existing Mind supporters from across a range of products and/or audiences. As our Team is expanding next year we are exploring the possibility of making this a biannual mailing with the second being sent in Q4 (early March",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Warm Audience ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "National Free Wills Network – Always on",
    "Describe your project, call to action and objective ": "Q1,2,3,and 4 This is our always available free wills offer in partnership with the National Free Wills Network. It encourages people to write their will for free with a local solicitor and consider leaving a gift to Mind. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Cold Audience ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "May appeal",
    "Describe your project, call to action and objective ": "Cash ask to warm supporters",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Lara Noormahomed",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Warm supporters ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Regular Giving ",
    "Describe your project, call to action and objective ": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Give a monthly gift to Mind",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Cold ABC1, Female skewed",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Cash/Valex (TBC)",
    "Describe your project, call to action and objective ": "Cash or valex during MHAW",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Cash ",
    "Describe your project, call to action and objective ": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Regular Giving - Magazine Inserts",
    "Describe your project, call to action and objective ": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Active Minds",
    "Describe your project, call to action and objective ": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "TBC",
    "Project Lead": "Leah Fuller",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "TBC",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Mind Mix",
    "Describe your project, call to action and objective ": "Briefing in 1,2,3, 4 A postal appeal for supporters who have given cash in the last 3 years, legacy pledgers, and past eventers. The call to action is a financial ask and the target is £60,000. *Please also outline any planned testing. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Alicia Shelly",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "GivePanel ongoing FY2324",
    "Describe your project, call to action and objective ": "Q1,2,3, and 4 GivePanel now offers an In Memory Facebook fundraiser, which we’ve tested in June 2022 ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "National Grief Awareness Week campaign",
    "Describe your project, call to action and objective ": "Q3 The nature of this campaign will change depending on the decision made re. the Christmas appeal. If we maintain the status quo (in-mem supporters received a bespoke Christmas appeal pack from retention) then they will receive a NGAW mailing very much like this year's which crosses into warm marketing (it presents our in-memory giving products).",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Remember Them – An In-Mem Christmas Campaign",
    "Describe your project, call to action and objective ": "A postal and email appeal, inviting current in-memory supporters to remember their loved ones with Mind at Christmas. The ask it to make a cash donation but there will also be an element of value exchange – perhaps a candle, a Christmas decoration or photo-frame at different price points. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "In-memory stewardship survey",
    "Describe your project, call to action and objective ": "Q1,We want in-memory supporters (tribute fund holders and cash donors) to complete a short e-survey to let us know what they’d like to see from our communications with them moving forwards. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Tribute fund holder thank you mailing",
    "Describe your project, call to action and objective ": "Q4 This is a postal communication to tribute fund holders who were active in the calendar year 2023.  Its sole purpose is to thank them for the money raised in 2023",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Emily East",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Christmas 2023 Cash Appeal & Reminder (Retention Only)",
    "Describe your project, call to action and objective ": "Q3 Our retention programme sends a Christmas appeal and reminder each year, both of which include a letter about the appeal and a cash ask. The postal appeal is accompanied by an email to the same audience a week after the postal appeal, along with some supporters who will only receive the email (not post). We will also send an email to warm supporters to Mind who have never given financially (e.g. campaigners or events) which we have done in previous years. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Elise Meyer",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Gift Aid Sept 2023 Mail & Email",
    "Describe your project, call to action and objective ": "Q2 We are planning to send a Gift Aid mailing and email to warm supporters where we don’t have a current Gift Aid declaration on their record. ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Elise Meyer",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "Warm Audience ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "September 2023 Supporter Magazine ",
    "Describe your project, call to action and objective ": "Q2 The Summer edition of our bi-annual supporter magazine is sent to our warm supporters each July",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Elise Meyer",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Summer 2023 Magazine ",
    "Describe your project, call to action and objective ": "Q2 The Summer edition of our bi-annual supporter magazine is sent to our warm supporters each July",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Elise Meyer",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Winter 2024 Magazine ",
    "Describe your project, call to action and objective ": "Q4",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "",
    "Project Lead": "Elise Meyer",
    "Team/Department": "FIDGE – Fundraising Individual Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Display": "",
    "Out of home": "",
    "Face to face": "",
    "Mailing": "",
    "Email": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  }
]

const FMGPlans = [
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Spring newsletter 29 March 2023",
    "Describe your project, call to action and objective": "Interview piece with Sarah Hughes. A topical article TBD. A case study on the Pacific Row / Walking the Coast. Updates page – 1 small article on key pieces of work – potentially With women in Mind TBD  ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "Fighting for better mental health of people living in poverty/Becoming a Truly ant-racist org/Supporting young people ",
    "What is your key message?": " ",
    "Project Lead": "Jodie Swanbo",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "All major donors and warm prospects",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Annual Review mailing (once available, date tbc between March - April  23)",
    "Describe your project, call to action and objective": "Share latest Annual Review and Accounts, and impact from the previous FY",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "All SDPs",
    "What is your key message?": "",
    "Project Lead": "Dzuliana Luksa-Soltanovic - although this lead will be changing in the coming weeks and allocated to another team ",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "All major donors and warm prospects",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Chelsea Flower Show garden relocation film",
    "Describe your project, call to action and objective": "release by 22 May (one year on from Chelsea) installment 3 of sponsor, Project Giving Back's 3 films, showcasing the garden's relocation, featuring garden designer, Andy Sturgeon and spokeseople (service users) from Mind in Furness",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "Fighting for people in poverty, together we are Mind, we connect Minds, we change Minds",
    "What is your key message?": "Create a film that can be used by the RHS, Mind, Project Giving Back, Andy Sturgeon and any approved third parties to: · help the public understand more about Andy’s Garden design for Mind and its connection to mental health - tell the story of how the garden is being used by Mind in Furness - raise awareness of mental health problems and break down the stigma surrounding it - encourage people to seek support, have conversation and get outside support for their mental health - raise awareness of Mind in our work",
    "Project Lead": "Georgi Peyok. Jasper Harvey (comms lead) to confirm any social strategy, Steph Cade (Press lead for press release in collaboration with other sponsor, Dunelm)",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "Project Giving Back, Mind Chelsea Flower Show audiences, Major Donors and guests from last year's show",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "MHAW - May 2023",
    "Describe your project, call to action and objective": "Update comms sent to donors ",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "All SDPs",
    "What is your key message?": "Update from org on MHAW",
    "Project Lead": "Across the organisation ",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "Major donors and warm prospects ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Service Visit - 16 May 2023",
    "Describe your project, call to action and objective": "High value supporter service collaboration - 1st in Q1 23/24 is NM x Tower Hamlets & Newham Mind. Coffee morning, brief tour of facilities, presentations by National Mind & TH&NM spokespersons",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "All SDPs",
    "What is your key message?": "Particular focus on fighting for people in poverty and becoming an anti-racist org through TH&NM services, but presentations will focus on the strategic links between NM and TH&NM and cover all three. For example, Sakinah (womens project used heavily by muslim community) is funded by national Mind.",
    "Project Lead": "Georgi Peyok/Jodie Swanbo",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "Major Donors (in particular this is a cultivation/donor coversion opportunity), Corporate partner and Trust & Foundation key/influential contacts, potentially celebrities and influencers - small & intimate vist (i.e. no more than 15 persons tbc)",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "",
    "Describe your project, call to action and objective": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Summer newsletter mailing August 2023",
    "Describe your project, call to action and objective": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "Jodie Swanbo",
    "Team/Department": "FMG – Fundraising Major Giving",
    "Who is your target audience?": "All major donors and warm prospects",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  }
]

const INFOPlans = [{
  "What type of moment is this project?": "Hum",
  "Project Name": "YP music PR campaign - Direct Line/Tinker Talker.",
  "Describe your project, call to action and objective": "PR campaign for YP Info",
  "Select the central strategic pillar that this activity links to": "",
  "What is your key message?": "If you're struggling with your mental health, you are not alone. Mind has information and resources to support you.",
  "Project Lead": "Kerry McLeod/Sarah Miles",
  "Team/Department ": "Info – Information",
  "Who is your target audience?": "Young people (11-18), parents, carers and educators",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
},
{
  "What type of moment is this project?": "Sing",
  "Project Name": "YouTube video project ",
  "Describe your project, call to action and objective": "YouTube-funded work to create 21 videos on 3 key MH topics: eating problems, depression, personality disorders. ",
  "Select the central strategic pillar that this activity links to": "We support minds",
  "What is your key message?": "",
  "Project Lead": "Rachel Q/Sarah Miles/Kerry McLeod",
  "Team/Department ": "Info – Information",
  "Who is your target audience?": "Adults ",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
},
{
  "What type of moment is this project?": "Hum",
  "Project Name": "YP printed leaflets: Welsh translations and Co-op funded leaflet ",
  "Describe your project, call to action and objective": "",
  "Select the central strategic pillar that this activity links to": "",
  "What is your key message?": "",
  "Project Lead": "",
  "Team/Department ": "Info – Information",
  "Who is your target audience?": "",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
},
{
  "What type of moment is this project?": "Sing",
  "Project Name": "Panic attacks animation - social promotion ",
  "Describe your project, call to action and objective": "Promotion of panic attacks animation on Anxiety pages of website",
  "Select the central strategic pillar that this activity links to": "We support minds",
  "What is your key message?": "Panic attacks are scary but there are things you can do to help yourself cope. ",
  "Project Lead": "Sarah Miles/Kerry McLeod",
  "Team/Department ": "Info – Information",
  "Who is your target audience?": "Primary ",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
},
{
  "What type of moment is this project?": "Hum",
  "Project Name": "New landing pages for Info (following IA project) ",
  "Describe your project, call to action and objective": "Restructure of adult info pages user journey  following Torchbox insights.   ",
  "Select the central strategic pillar that this activity links to": "We support minds",
  "What is your key message?": "It's easy to find the information you need. ",
  "Project Lead": "Kerry McLeod/Sarah Miles/Helen Leech ",
  "Team/Department ": "Info – Information",
  "Who is your target audience?": "All adults ",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
},
{
  "What type of moment is this project?": "Hum",
  "Project Name": "COMING SOON (by year end) - new info products for adults: 1. Menopause2. Coping after a suicide attempt",
  "Describe your project, call to action and objective": "New information content on two topics in response to user need. ",
  "Select the central strategic pillar that this activity links to": "We support minds",
  "What is your key message?": "",
  "Project Lead": "Sarah Miles/Kerry McLeod/Helen Leech",
  "Team/Department ": "Info",
  "Who is your target audience?": "Adults",
  "Website": "",
  "Mind at Work": "",
  "Emails": "",
  "Networks": "",
  "Retail": "",
  "Supporter comms": "",
  "Social media": "",
  "Internal": "",
  "Media": "",
  "MPs": "",
  "Celebrity amplifier": "",
  "Corporate amplifier": "",
  "Outdoor": "",
  "M": "",
  "T": "",
  "W": "",
  "F": "",
  "S": "",
  "": ""
}]

const ICPlans = [
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "All Staff Briefing",
    "Describe your project, call to action and objective": "Internal comms event via Zoom",
    "Select the strategic development priority that this activity links to": "Updates on all SDPs and pillars.",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Together, we are Mind.",
    "Project Lead": "Sarah Giwa-Amu",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind and Retail Staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "AskMET Live",
    "Describe your project, call to action and objective": "Online Q&A session with Exec Team ",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Together, we are Mind.Promoting an open culture and transparent decision making.",
    "Project Lead": "Sarah Giwa-Amu",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind Staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Gender Pay Gap report expected",
    "Describe your project, call to action and objective": "Mandatory reporting",
    "Select the strategic development priority that this activity links to": "N/A",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Becoming an equitable place to work.",
    "Project Lead": "People team",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind and Retail Staff",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Maternal Mental Health Week",
    "Describe your project, call to action and objective": "TBC Likely internal event and intranet blogs",
    "Select the strategic development priority that this activity links to": "N/A",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Together, we are Mind",
    "Project Lead": "Kate Camp",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Mental Health Awareness Week",
    "Describe your project, call to action and objective": "Internal comms and events to highlight and complement external campaign theme: COLDetails TBC",
    "Select the strategic development priority that this activity links to": "Supporting people living in poverty",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "We understand financial worries can impact our mental health.Mind is a responsible employer.Mind is here for everyone.",
    "Project Lead": "Aisha Patel & Tanya Mohammed",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Anniversary of murder of George Flloyd",
    "Describe your project, call to action and objective": "TBC Likely blog or video from Sarah Hughes",
    "Select the strategic development priority that this activity links to": "Becoming an anti-racist organisation",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "We are committed to becoming an anti-racist organisation. ",
    "Project Lead": "Sarah Giwa-Amu",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "All federation staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Pride month",
    "Describe your project, call to action and objective": "Range of internal events, intranet posts. Details TBC",
    "Select the strategic development priority that this activity links to": "Supporting Young People, with a focus on trauma",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind is here for everyone",
    "Project Lead": "Kate Camp",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "All federation staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Volunteers Week ",
    "Describe your project, call to action and objective": "Sharing volunteers' stories on our intranet, Open Hub and through retail newsletter. Spotlight session in ASB",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind could not operate without its army of passionate volunteers. Thank youCTA: Volunteer with us",
    "Project Lead": "Maria Carbajales and Sarah Giwa-Amu",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "All federation staff",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "X",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Refugee Week",
    "Describe your project, call to action and objective": "TBC",
    "Select the strategic development priority that this activity links to": "Becoming an anti-racist organisationSupporting people living in poverty",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind is here for everyone",
    "Project Lead": "TBC",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind and Retail Staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Thankathon (TBC)",
    "Describe your project, call to action and objective": "A day of thanks to everyone who supports our work. Whole org involvement.",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "TBC",
    "Project Lead": "Jen Brazier",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "All federation staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Disability Pride Month",
    "Describe your project, call to action and objective": "TBC",
    "Select the strategic development priority that this activity links to": "",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "Mind is here for everyone",
    "Project Lead": "TBC",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "South Asian Heritage Month",
    "Describe your project, call to action and objective": "TBC",
    "Select the strategic development priority that this activity links to": "Becoming an anti-racist organisation",
    "Select the central strategic pillar that this activity links to": "Together, we are Mind",
    "What is your key message?": "Together, we are Mind",
    "Project Lead": "Aisha Patel",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "National Mind Staff",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "BAYO Manchester launch event",
    "Describe your project, call to action and objective": "TBC",
    "Select the strategic development priority that this activity links to": "Becoming an anti-racist organisation",
    "Select the central strategic pillar that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "Ariel Breaux-Torres",
    "Team/Department": "IC - Internal Comms",
    "Who is your target audience?": "All federation staff, external, communities",
    "Website": "X",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "X",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  }
]

const MediaPlans = [
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Fund the Hubs Phase 2",
    "Describe your project, call to action and objective": "We are commisisoning a PR agency to support with the next burst of the campaign, using £10k budget from CYP underspend. We also have a grandparents/parents poll that will generate news hooks to talk about issue of CYP MH with influential Tory outlets e.g. Telegraph",
    "Select the strategic development priority that this activity links to": "YP",
    "What is your key message?": "Pandemic has had disproportionate impact on YP who face long waiting lists for CAMHS or are turned away altogether. We want UK Gov't to fund network of early intervention hubs across England to offer range of support in non-clinical non-threatening environment",
    "Project Lead": "Shelly Naylor",
    "Team/Department": "Media - Media",
    "Who is your target audience?": "UK Government, Chancellor, young people, parents, CAMHS professionals",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Local Minds in Wales - activity report",
    "Describe your project, call to action and objective": "We have carried out a report into the work done by local Minds in Wales and will be promoting that to media throughout the country",
    "Select the strategic development priority that this activity links to": "CYP, Poverty",
    "What is your key message?": "Local Minds in Wales are supporting more people than ever before. The work that local Minds do benefits communities across the country",
    "Project Lead": "Lucy Nichol / Luke Merlini",
    "Team/Department": "Media - Media",
    "Who is your target audience?": "Welsh public, Welsh Government, local authorities, Local Health Boards",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Young person in-patient report",
    "Describe your project, call to action and objective": "Focussing on the issues young people face while receiving treatment at in-patient services",
    "Select the strategic development priority that this activity links to": "CYP ",
    "What is your key message?": "Young people are being failed and services must do better",
    "Project Lead": "Shelly Naylor",
    "Team/Department": "Media - Media",
    "Who is your target audience?": "UK Government, young people, parents, CAMHS professionals",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Direct Line & Mind collaboration",
    "Describe your project, call to action and objective": "Survey around CYP and mental health, including a 'moment' with rapper Marc Jones",
    "Select the strategic development priority that this activity links to": "CYP",
    "What is your key message?": "Importance of self care and acceptance. Campaign is based around the concept of 'love yourself'",
    "Project Lead": "Shelly Naylor",
    "Team/Department": "Media - Media",
    "Who is your target audience?": "Young People, parents, general public",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Hum",
    "Project Name": "Cost of Living polling",
    "Describe your project, call to action and objective": "Polling on the impact of cost of living on people's mental health",
    "Select the strategic development priority that this activity links to": "CYP, Poverty, Race",
    "What is your key message?": "How the cost of living is impacting people in England & Wales, and what needs to be done",
    "Project Lead": "Will Berrington",
    "Team/Department": "Media - Media",
    "Who is your target audience?": "UK Govt, local authorities, general public",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
]

const SportPlans = [
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "We Are Undefeatable (Hum - bursts in August & Autumn dates tbc) ",
    "Describe your project, call to action and objective": "Multi year, multi-million campaign led by Richmond Group of Charities supported by Mind to get people with long term health conditions to move in their own way.",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "Jack Holloway",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "People with long term health conditions including MH problems ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "Mind's physical activity sector support offer (jigsaw) - Hum Sept date tbc ",
    "Describe your project, call to action and objective": "Funded by Sport England we will be launching new tools to support the sport and physical activity sector ",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "",
    "Project Lead": "Karen Shaw ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "Sport and physical activity sector only ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "SIng",
    "Project Name": "Play their way (working title name to be confirmed) - Hum dates etc June 2023 **EXACT DATES TBC**",
    "Describe your project, call to action and objective": "Children's coaching collaborative is led by Sport England and will be organising a campaign similar to the We are undefeatable/This Girl Can aimed at sports coaches to support YP to become active. We are part of the planning for the campaign ",
    "Select the central strategic pillar that this activity links to": "",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "YP have the right to be active - great coaching is rights based ",
    "Project Lead": "James Durcan ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "Sports coaches and youth workers ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "SIng",
    "Project Name": "AoC Sport National Champions - Hum (see separate comms plan) - NOW COMPLETE ",
    "Describe your project, call to action and objective": "Large event for college aged YP sports ",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "Young people ",
    "What is your key message?": "We're Mind and we’re here to support you. Opportunity for Mind to gain soundbites from YP ",
    "Project Lead": "James Durcan ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "YP/ General public ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "EFL Legacy grants - Hum tbc Q1/2 ",
    "Describe your project, call to action and objective": "TBC press launch of 10 legacy projects /social media spotlight if appropriate ",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Whoever you support, Mind supports you. ",
    "Project Lead": "Jack Holloway/Cameron Milller/Hayley Jarvis ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "General public /Sport and physical activity sector ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "ASICS Get Active Connector Launch - Hum 6/7 June 2023 ",
    "Describe your project, call to action and objective": "Press launch regionally with 4 x projects and a national event/launch with Mind and ASICS ",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Being active supports you to stay well and live well. ",
    "Project Lead": "Cameron Milller/Hayley Jarvis ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "General public /Sport and physical activity sector ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  },
  {
    "What type of moment is this project?": "Sing",
    "Project Name": "ASICS Feeling in Focus joint campaign - SING? (may be listed on partnerships?) ",
    "Describe your project, call to action and objective": "Joint Lived Ex led campaign about a personal best not being about a number - about how PA makes you feel ",
    "Select the central strategic pillar that this activity links to": "We support minds",
    "Select the strategic development priority that this activity links to": "",
    "What is your key message?": "Being active is about how it makes you feel ",
    "Project Lead": "Megan/Hayley/Jack ",
    "Team/Department": "Sport - Sport",
    "Who is your target audience?": "General public /Sport and physical activity sector ",
    "Website": "",
    "Mind at Work": "",
    "Emails": "",
    "Networks": "",
    "Retail": "",
    "Supporter comms": "",
    "Social media": "",
    "Internal": "",
    "Media": "",
    "MPs": "",
    "Celebrity amplifier": "",
    "Corporate amplifier": "",
    "Outdoor": "",
    "M": "",
    "T": "",
    "W": "",
    "F": "",
    "S": "",
    "": ""
  }
]